In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/PremierLeague25_26.csv")

In [3]:
df_clean = df.copy()

In [4]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

df_clean.isnull().sum()[df_clean.isnull().sum() > 0]

Rows: 380
Columns: 132

BFDH          1
BFDD          1
BFDA          1
BMGMH         2
BMGMD         2
BMGMA         2
BVH           2
BVD           2
BVA           2
CLH          98
CLD          98
CLA          98
LBH          94
LBD          94
LBA          94
PSH         170
PSD         170
PSA         170
BFEH         20
BFED         20
BFEA         20
P>2.5       170
P<2.5       170
BFE>2.5      20
BFE<2.5      20
AHh           1
PAHH        170
PAHA        170
BFEAHH       20
BFEAHA       20
BFDCH         8
BFDCD         8
BFDCA         8
BVCH          8
BVCD          8
BVCA          8
CLCH        120
CLCD        120
CLCA        120
LBCH         99
LBCD         99
LBCA         99
PSCH        170
PSCD        170
PSCA        170
BFECH        22
BFECD        22
BFECA        22
PC>2.5      170
PC<2.5      170
BFEC>2.5     22
BFEC<2.5     22
PCAHH       170
PCAHA       170
BFECAHH      22
BFECAHA      22
dtype: int64

In [6]:
df_clean[["BFECAHH", "BFECAHA"]].head(20)

BFECAHH    22
BFECAHA    22
dtype: int64

In [9]:
df_clean[["BFECAHH", "BFECAHA"]].describe()

          BFECAHH     BFECAHA
count  358.000000  358.000000
mean     1.990782    1.998883
std      0.096875    0.097022
min      1.810000    1.740000
25%      1.910000    1.920000
50%      1.980000    2.000000
75%      2.060000    2.077500
max      2.320000    2.220000

In [10]:
df_clean[["BFECAHH", "BFECAHA"]].isnull().sum()

BFECAHH    22
BFECAHA    22
dtype: int64

BFECAHH    22
BFECAHA    22
dtype: int64

In [12]:
df_clean[[
    "Date",
    "Time",
    "HomeTeam",
    "AwayTeam",
    "FTHG",
    "FTAG",
    "FTR"
]].dtypes

Date          str
Time          str
HomeTeam      str
AwayTeam      str
FTHG        int64
FTAG        int64
FTR           str
dtype: object

In [16]:
df_clean["Date"] = pd.to_datetime(
    df_clean["Date"],
    dayfirst=True
)

In [17]:
df_clean["Date"].dtype

dtype('<M8[us]')

In [18]:
numeric_match_columns = [
    "FTHG", "FTAG",
    "HTHG", "HTAG",
    "HS", "AS",
    "HST", "AST",
    "HF", "AF",
    "HC", "AC",
    "HY", "AY",
    "HR", "AR"
]

df_clean[numeric_match_columns].min()

FTHG    0
FTAG    0
HTHG    0
HTAG    0
HS      1
AS      3
HST     0
AST     0
HF      3
AF      3
HC      0
AC      0
HY      0
AY      0
HR      0
AR      0
dtype: int64

In [19]:
(df_clean["HST"] > df_clean["HS"]).sum()

np.int64(0)

In [20]:
(df_clean["AST"] > df_clean["AS"]).sum()

np.int64(0)

In [21]:
(df_clean["HTHG"] > df_clean["FTHG"]).sum()

np.int64(0)

In [22]:
(df_clean["HTAG"] > df_clean["FTAG"]).sum()

np.int64(0)

In [23]:
def calculate_result(row):
    if row["FTHG"] > row["FTAG"]:
        return "H"
    elif row["FTHG"] < row["FTAG"]:
        return "A"
    else:
        return "D"

In [24]:
calculated_results = df_clean.apply(
    calculate_result,
    axis=1
)

In [26]:
(calculated_results != df_clean["FTR"]).sum()

np.int64(0)

In [27]:
df_clean[
    df_clean["BFECAHH"].isnull() |
    df_clean["BFECAHA"].isnull()
][
    [
        "Date",
        "HomeTeam",
        "AwayTeam",
        "BFECAHH",
        "BFECAHA"
    ]
]

          Date        HomeTeam        AwayTeam  BFECAHH  BFECAHA
328 2026-04-20  Crystal Palace        West Ham      NaN      NaN
329 2026-04-21        Brighton         Chelsea      NaN      NaN
330 2026-04-22     Bournemouth           Leeds      NaN      NaN
331 2026-04-22         Burnley        Man City      NaN      NaN
332 2026-04-24      Sunderland   Nott'm Forest      NaN      NaN
333 2026-04-25          Fulham     Aston Villa      NaN      NaN
334 2026-04-25       Liverpool  Crystal Palace      NaN      NaN
335 2026-04-25        West Ham         Everton      NaN      NaN
336 2026-04-25          Wolves       Tottenham      NaN      NaN
337 2026-04-25         Arsenal       Newcastle      NaN      NaN
338 2026-04-27      Man United       Brentford      NaN      NaN
339 2026-05-01           Leeds         Burnley      NaN      NaN
340 2026-05-02       Brentford        West Ham      NaN      NaN
341 2026-05-02       Newcastle        Brighton      NaN      NaN
342 2026-05-02          Wolves      Sunderland      NaN      NaN
343 2026-05-02         Arsenal          Fulham      NaN      NaN
344 2026-05-03     Bournemouth  Crystal Palace      NaN      NaN
345 2026-05-03      Man United       Liverpool      NaN      NaN
346 2026-05-03     Aston Villa       Tottenham      NaN      NaN
347 2026-05-04         Chelsea   Nott'm Forest      NaN      NaN
348 2026-05-04         Everton        Man City      NaN      NaN
349 2026-05-09       Liverpool         Chelsea      NaN      NaN

In [28]:
[col for col in df_clean.columns if "BFECAH" in col]

['BFECAHH', 'BFECAHA']

In [29]:
[col for col in df_clean.columns if "BFECA" in col]

['BFECA', 'BFECAHH', 'BFECAHA']

In [30]:
match_duplicates = df_clean.duplicated(
    subset=["Date", "HomeTeam", "AwayTeam"],
    keep=False
)

df_clean[match_duplicates][
    ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG"]
]

Empty DataFrame
Columns: [Date, HomeTeam, AwayTeam, FTHG, FTAG]
Index: []

In [31]:
match_duplicates.sum()

np.int64(0)

In [32]:
print(df_clean["FTR"].unique())
print(df_clean["HTR"].unique())

<StringArray>
['H', 'D', 'A']
Length: 3, dtype: str
<StringArray>
['H', 'D', 'A']
Length: 3, dtype: str

In [33]:
print("Missing home teams:", df_clean["HomeTeam"].isnull().sum())
print("Missing away teams:", df_clean["AwayTeam"].isnull().sum())

Missing home teams: 0
Missing away teams: 0

In [34]:
print("Unique home teams:", df_clean["HomeTeam"].nunique())
print("Unique away teams:", df_clean["AwayTeam"].nunique())

Unique home teams: 20
Unique away teams: 20

In [35]:
print(sorted(df_clean["HomeTeam"].unique()))

['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds', 'Liverpool', 'Man City', 'Man United', 'Newcastle', "Nott'm Forest", 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']

In [36]:
home_teams = set(df_clean["HomeTeam"].unique())
away_teams = set(df_clean["AwayTeam"].unique())

print("Teams only appearing as home:", home_teams - away_teams)
print("Teams only appearing as away:", away_teams - home_teams)

Teams only appearing as home: set()
Teams only appearing as away: set()

In [37]:
print("First match:", df_clean["Date"].min())
print("Last match:", df_clean["Date"].max())

First match: 2025-08-15 00:00:00
Last match: 2026-05-24 00:00:00

In [38]:
print(df_clean["Date"].sort_values().head())
print(df_clean["Date"].sort_values().tail())

0   2025-08-15
1   2025-08-16
2   2025-08-16
3   2025-08-16
4   2025-08-16
Name: Date, dtype: datetime64[us]
372   2026-05-24
371   2026-05-24
370   2026-05-24
373   2026-05-24
379   2026-05-24
Name: Date, dtype: datetime64[us]

In [40]:
final_missing = df_clean.isnull().sum()

final_missing[final_missing > 0]

BFDH          1
BFDD          1
BFDA          1
BMGMH         2
BMGMD         2
BMGMA         2
BVH           2
BVD           2
BVA           2
CLH          98
CLD          98
CLA          98
LBH          94
LBD          94
LBA          94
PSH         170
PSD         170
PSA         170
BFEH         20
BFED         20
BFEA         20
P>2.5       170
P<2.5       170
BFE>2.5      20
BFE<2.5      20
AHh           1
PAHH        170
PAHA        170
BFEAHH       20
BFEAHA       20
BFDCH         8
BFDCD         8
BFDCA         8
BVCH          8
BVCD          8
BVCA          8
CLCH        120
CLCD        120
CLCA        120
LBCH         99
LBCD         99
LBCA         99
PSCH        170
PSCD        170
PSCA        170
BFECH        22
BFECD        22
BFECA        22
PC>2.5      170
PC<2.5      170
BFEC>2.5     22
BFEC<2.5     22
PCAHH       170
PCAHA       170
BFECAHH      22
BFECAHA      22
dtype: int64

In [42]:
df_clean.to_csv(
    "../data/processed/PremierLeague25_26_clean.csv",
    index=False
)